export const START_LOADING_ALL_POST = 'START_LOADING_ALL_POST';
export const SUCCESSFUL_LOADING_ALL_POST = 'SUCCESSFUL_LOADING_ALL_POST';
export const FAILED_LOADING_ALL_POST = 'FAILED_LOADING_ALL_POST';